[package]
name = "dirp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.1.0"
threadpool = "1.8.1"
timer = "0.2.0"
chrono = "0.4.23"
tui = "0.19.0"
crossterm = "0.26.1"
trash = "3.0.1"